//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.pedido = new HashSet<pedido>();
            this.pedido_pen = new HashSet<pedido_pen>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int idempleado { get; set; }
        public int idtipo { get; set; }
        public string ife { get; set; }
        public string nombre { get; set; }
        public string ap_mat { get; set; }
        public string ap_pat { get; set; }
        public string domicilio { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string telefono { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public System.DateTime fecha_alta { get; set; }
    
        public virtual tipousuario tipousuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_pen> pedido_pen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
