//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IncerEntities5 : DbContext
    {
        public IncerEntities5()
            : base("name=IncerEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<pedido_auto> pedido_auto { get; set; }
        public virtual DbSet<pedido_pen> pedido_pen { get; set; }
        public virtual DbSet<provedor> provedor { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<memoria_pedido> memoria_pedido { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
    }
}
