//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido_auto()
        {
            this.venta = new HashSet<venta>();
        }
    
        public int idped_auto { get; set; }
        public int idpedido { get; set; }
        public int idcliente { get; set; }
        public string piezas { get; set; }
        public decimal cantidad { get; set; }
        public string codigo { get; set; }
        public decimal precio_vent { get; set; }
        public decimal precio_comp { get; set; }
    
        public virtual pedido_pen pedido_pen { get; set; }
        public virtual pedido_pen pedido_pen1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
